language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: S1xZEeI448nnvUI99NtkWy1G7t86cjoYx8bjUt331RMKGqKzDpPHv4zc8cRM10f1/J0rBvDyxcZMyo1EZFPCIoswD1pBTECDoyJ5uJPeUX3OGNqOiLcT03jqWSFbqBa3UxCYaKApY2Ch7C9RPCTcK1C4BI4AgqRsOrxrnc+fq0+HrZofAJVV6fHkwsOMzp3gtUtzIwpr0F14bz7VZ2ltUwkFAiZUTEkAETyiFI6oE4Rm2qOeS4YoCzIdfIlq8dOyeVYxq/oiSSFZfh8hln3n3o0QpXHJcjJeUB37mOADZMSamDFqFbmH2a2+1iM+eie0dHXmSw3aA1533kgjTbsI89MRUOoz9UpVEPf1i0eGN0UkPy8v+9ql2g/WWOQXM9cg1UNfoNgSLU6TmTKdkahnuxx0uciEWmshNL8M40wSgNdaroH8PDkqUz2jAHVALaYoKeVd5n6JoRyMXQ9wNya8VAdFqCNTjHomD3yTvPAu9Ql01KLVKwhUVheFkmJzH/xKMBlJRTm9sYZAJIjpfPqe2qD9wYQQuUqEXZgQEo91qcdrsgi2PJWoCy8w4Ju8QVe+qdGbSbUB/kvpfLXvWzLm/g/XJG3ZcfLw3KttNiVdjzIj2cS2AOSVjMhkZLaklcpHu8LuDZuHTadDrnu9jBjImFcAfNXL3gOgLlVTVrdVPdA=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  directories:
  - node_modules
before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh
before_script:
- "./.build_scripts/lint.sh"
- npm test
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"
