language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: 0ZJYayCy4VJVfGWcVRCbDLbYKZScZy6FeUuigTsqDl3sVIrcM7vvAtgq0Q5PLv0psRf6f2dRbcBJOLeQMXAkpRkblqXk0bEZegbmaivwXgN/NmtkGWCZfYdZKm8L29qzPGPsrA8cziJBIuLh2BcTNP2EqtPxuwuq9JsVHPWLJNGqk35SiItqZIUwV85URLgEdYsQ8gS9ittsHzY3djPrwEQFj4BO+DAXcYzCQRfK0+Ru4cbAppRnkpXh4bcwckd+a3ylP+/jISY1cn8V7wC2kspRx5eG3FEov1aeP29zW1N0zPx3jPF7p67ZuUUqXcCrjlNdyfL+n9vT2M5DQ+bOtQjnkib8wgkINO+Cb33TiL4aOwiFUM/VWyAxK1QOaZcq07BZ1Erh+eAx9s1g5R2UN2uOPT1rkK1/Ayej+Gk1oJDlP9DTQ2XoN4TOBhpuKtDgLLcAaF5rKpROnRG3dM9GCovVx/Esc3MeKsjgqtGUbsvLn9wLsKnu5OQ3Bhnk5z1sJZMYzXrCRqpsl6dyqaC2pCOnOO73H3gQFN8oX+Xog70/0pcCQlZrcj035MOAYIkiPvxGXY7Ul2XWqqca3KYgCAmH25F0ZSudyZVw+UCQ8HgozBuLaCShrNboum+2XN4IR5a0lBxCqTV3tjiSNMajwFooCPt52lVlD9c9n87Zddw=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  directories:
  - node_modules
before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh
before_script:
- "./.build_scripts/lint.sh"
- npm test
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"
