language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: Fd7IQbMc3JkfENdnAxjwxhcjJVwvih4WF54qP23UaYCs8bdDJkzBtkhx+YiPvXxJa/S65bjvE7sQyO+EwEn8E77mR1G/zmpj/UC58IWXOxlp/uYQTQQwFnz434mRtr3Y/qj8qwNX+CPnNS/TppIuykU/7t4keuTJPDgid+JDCUKE8JUDLfXzRrgS0ujr4UYHkLz/s/rHtqzs7e0nEK7oo5Mz24F7kyHehfc26Oe1Wg1J9agbTK4O9/oObtFdljd8RHbrGWaozF28cKwG+rDoYLf1/gTIuWruY+AjQMx6dI43AJC564I7Qid6lTNlTNBoz+IEO458+9dZX1WlTu1vg+a9/CrQ3t9cb8L0Q2Zog/Ugbs8Q0ByF91pNgqGBK+tYVnkrjV5VouGU9Sx5AnXoBP1us74BHFNIwNGalrEbhM1QiCAZGJv+hVok+fsFrfaF6iKACdyQDePb+Qse8lM2BuoyRnicolSoO1BVJacYcqfMrYvEButDU3C5fezNngdRxtn4tpPRslivt9UX1MxQS8SHQD0x6YCU5YuzntMQuTOS7Dizz2uqvwA63Et702kwCTbtm5u6+R8qQHmF7onyviJW9EN1YhkQXZuR1TKyzUr+CQScKfmhOJweq+I3zqGXkPzJhi0HCpSpJfR3gqU2u+BDkbL3jW8eGrHnQnLxey4=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  directories:
  - node_modules
before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh
before_script:
- "./.build_scripts/lint.sh"
- npm test
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"
