language: node_js
node_js:
- '4'
env:
  global:
  - CXX=g++-4.8
  - DEPLOY_BRANCH=master
  - secure: SLspNlOYP1ywQXYegpRPxOOQoOyaXJkEvtZVZokIne3EARDMD02cAFkCaXDMfDcyEbtaADwDzJnCNKEFyWmC/KXK4yQp+Woym4sk5M1vkt/PrHrNZYA4Vhqbx92iTpWZetJtNiMFhzFuqlhdYd/b7UG+Cx/X+4ermKyDhV2PaR3TtZJCYJomGyBdyhNToWFLgihYx5DwbuJe9EkCKhi8EMRbLXDxVhnfPfbLwaxfwT88CgxgrxY7sdrDRGdcqj7+uG54zm5Kfzjffb7k3SIL1d5Dni2/1H23oJKgfHiUywusspnFpcMnefVLh9tVxKp0G3HNNC0O75EYZBKgVf49k8KgDz2w1Ei/8NUvfNuGCu3stj7O7aTS0X3elvc4TzvQJ5pvtPwuKa+HsYfb091KCWiMi17O7WCm0oBwJZ+9T6v+AVtZlEWyB3dLDeEISsmhqj1ydGYH/JIzOcfBx71jSA8njMgw0SwGd55732bUPNFEuWMPCiZN5EQ+5J9BxwLTmaG7Nrq2UzJdKm5c+ZjhUz9W6CTjZYaMeDUyvEtBHcwmVGVJbejImtOilxFBH0Ic4C+nLfOeV1blP4jOZojFAimSdGaWXs6X+43WpOeArHYHazfsFRkdNBbKjSfwhasfEP/d0Rvf3DfgYFLpYaKwk0X5ijXwm3VwXpzkjnc5ueQ=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  apt: true
  directories:
  - node_modules
before_install:
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/lint.sh
before_script:
- "./.build_scripts/lint.sh"
- npm test
script:
- npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: ".build_scripts/deploy.sh"
  on:
    branch: "${DEPLOY_BRANCH}"
